# Generated by Django 5.2.8 on 2026-02-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PARTICULAR', 'Particular'), ('INSTITUCIONAL', 'Institucional')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioInstitucional',
            fields=[
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='institucional', serialize=False, to='beneficiarios.beneficiario')),
                ('nombre_institucion', models.CharField(max_length=200)),
                ('tipo_institucion', models.CharField(choices=[('CASA_HOGAR', 'Casa Hogar'), ('FUNDACION', 'Fundación'), ('ASOCIACION', 'Asociación'), ('OTRO', 'Otro')], max_length=50)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombre_representante', models.CharField(max_length=30)),
                ('apellido_representante', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'beneficiarios_institucionales',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioParticular',
            fields=[
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='particular', serialize=False, to='beneficiarios.beneficiario')),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'beneficiarios_particulares',
            },
        ),
    ]
