# Generated by Django 5.2.8 on 2026-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='email',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
