# Generated by Django 5.2.8 on 2026-02-12 01:52

import apps.donaciones.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_donacion', models.DateField(default=datetime.date.today)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada')], default='ACTIVA', max_length=15)),
            ],
            options={
                'db_table': 'donaciones',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateField(validators=[apps.donaciones.utils.validar_fecha_entrega])),
                ('recibida_por', models.CharField(blank=True, help_text='Persona que recibe físicamente la entrega', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('REALIZADA', 'Realizada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=15)),
            ],
            options={
                'db_table': 'entregas',
            },
        ),
        migrations.CreateModel(
            name='EntregaAnulada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_anulacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entregas_anuladas',
            },
        ),
        migrations.CreateModel(
            name='ItemDonacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='DISPONIBLE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'items_donacion',
            },
        ),
    ]
