# Generated by Django 5.2.8 on 2026-02-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaciones', '0001_initial'),
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones', to='donantes.donante'),
        ),
    ]
