# Generated by Django 5.2.8 on 2026-02-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0002_initial'),
        ('donaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='beneficiarios.beneficiario'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='registrada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaanulada',
            name='anulada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones_entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaanulada',
            name='entrega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='donaciones.entrega'),
        ),
        migrations.AddField(
            model_name='itemdonacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='donaciones.categoria'),
        ),
        migrations.AddField(
            model_name='itemdonacion',
            name='donacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donaciones.donacion'),
        ),
        migrations.AddField(
            model_name='itemdonacion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='donaciones.itemdonacion'),
        ),
    ]
