# Generated by Django 5.2.8 on 2026-02-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_donante', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICO', 'Juridico')], max_length=10)),
                ('email', models.EmailField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'donantes',
            },
        ),
        migrations.CreateModel(
            name='DonanteJuridico',
            fields=[
                ('donante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='juridico', serialize=False, to='donantes.donante')),
                ('razon_social', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombre_representante', models.CharField(max_length=30)),
                ('apellido_representante', models.CharField(max_length=30)),
                ('cargo_representante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'donantes_juridicos',
            },
        ),
        migrations.CreateModel(
            name='DonanteNatural',
            fields=[
                ('donante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='natural', serialize=False, to='donantes.donante')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'donantes_naturals',
            },
        ),
    ]
